### ISSUE TITLE
Timing issue in test_signal_shutdown_in_task?

### ISSUE THREAD

**Issue by guettli** [djangsters/redis-tasks#99]
Just for fun I added `time.sleep(1)` in taskwait():
```
(redis-tasks) guettli@yoga15:~/projects/redis-tasks$ git diff
diff --git a/tests/test_workerprocess.py b/tests/test_workerprocess.py
index 96920a3..463f52f 100644
--- a/tests/test_workerprocess.py
+++ b/tests/test_workerprocess.py
@@ -278,6 +278,7 @@ def test_execute_task(mocker, settings, time_mocker):
 def taskwait():
     with multiprocessing.connection.Client(os.environ['RT_TEST_SOCKET']) as conn:
         conn.send("A")
+        time.sleep(1)
         try:
             time.sleep(10)
             conn.send("C")
```

This results in this error:
```
__________________________________________________________________________ test_signal_shutdown_in_task __________________________________________________________________________

suprocess_socket = <multiprocessing.connection.Listener object at 0x7f0230fbd190>

    def test_signal_shutdown_in_task(suprocess_socket):
        queue = QueueFactory()
        task = queue.enqueue_call(taskwait)
        wp = WorkerProcess([queue])
        process = multiprocessing.Process(target=wp.run)
        process.start()
    
        with suprocess_socket.accept() as taskconn:
            assert taskconn.poll(1)
            assert taskconn.recv() == "A"
            os.kill(process.pid, signal.SIGTERM)
            assert taskconn.poll(1)
>           assert taskconn.recv() == "B"

tests/test_workerprocess.py:310: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.8/multiprocessing/connection.py:250: in recv
    buf = self._recv_bytes()
/usr/lib/python3.8/multiprocessing/connection.py:414: in _recv_bytes
    buf = self._recv(4)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <multiprocessing.connection.Connection object at 0x7f02319cf160>, size = 4, read = <built-in function read>

    def _recv(self, size, read=_read):
        buf = io.BytesIO()
        handle = self._handle
        remaining = size
        while remaining > 0:
            chunk = read(handle, remaining)
            n = len(chunk)
            if n == 0:
                if remaining == size:
>                   raise EOFError
E                   EOFError

/usr/lib/python3.8/multiprocessing/connection.py:383: EOFError
------------------------------------------------------------------------------- Captured log call --------------------------------------------------------------------------------
INFO     redis_tasks.task:task.py:145 Task tests.test_workerprocess.taskwait() [2cb18aa6-d9f6-4ebe-8f5a-e118925b7b57] enqueued
---------------------------------------------------------------------------- Captured stderr teardown ----------------------------------------------------------------------------
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/guettli/projects/redis-tasks/redis_tasks/worker_process.py", line 117, in run
    self.maybe_shutdown()
  File "/home/guettli/projects/redis-tasks/redis_tasks/worker_process.py", line 235, in maybe_shutdown
    raise ShutdownRequested()
redis_tasks.worker_process.ShutdownRequested
============================================================================ short test summary info =============================================================================
FAILED tests/test_workerprocess.py::test_signal_shutdown_in_task - EOFError
=
```

Version:
```
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
```

It works on my machine if I use `time.sleep(0.001)`, but fails with `time.sleep(0.01)` (or higher values)

To be honest, I have not understood `test_signal_shutdown_in_task` up to now.

I guess you want the task to be able to catch the SIGTERM and be able to do something, before the task stops to work.

Is this catching of `WorkerShutdown`, then doing some clean-up before finishing a documented behavior? (I like this behavior)

**Comment by vasilty** [comment]
With this change the task definitely waits before the `try` and thus the exception is not handled. Not sure I understand what the idea is. The general idea is to catch SIGTERM and do task re-scheduling if the task is reentrant.

**Comment by guettli** [comment]
The idea of this issue that the following patch is still valid would solve a timing issue:

https://github.com/djangsters/redis-tasks/pull/95/files

Maybe at the moment no test fails, but sooner or later it is likely that it will come again.
